---
title: "ccbr1137"
author: "Samantha Sevilla"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
#dirs
parent_dir="~/../../Volumes/ccbr1137/"
input_dir = "~/../../Volumes/ccbr1137/analysis/ipa/"
output_dir = "~/../../Volumes/ccbr1137/analysis/r_analysis_220827/"
dir.create(file.path(output_dir), showWarnings = FALSE)
```

```{r thresholds}
# input files
file_list=c("upstream_analysis_kd-sh1.txt","upstream_analysis_kd-sh2.txt")

# group list
mol_list=c("cytokine","transcription regulator","growth factor","kinase","transmembrane receptor")

```

```{r pkg, echo=FALSE, warning=FALSE, include=FALSE}
# package list
#list.of.packages=c("BiocManager","tidyr","DT","RUVSeq","RColorBrewer","textshape",
 #                  "pheatmap","grid","dplyr","EnhancedVolcano","edgeR","DESeq2","ggplot2","plotly",
  #                 "msigdbr","clusterProfiler","ggpubr","ggridges","factoextra","gplots","ReactomePA",species_db)
list.of.packages=c("ggplot2","tidyverse","scales","cowplot")

#install as needed
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) BiocManager::install(new.packages)

# source functions
source('ccbr1137_core_functions.R')

# load packages
invisible(lapply(list.of.packages, library, character.only = TRUE))

#negate
`%ni%` <- Negate(`%in%`)
```

```{r, echo=FALSE, message=FALSE,warning=FALSE}
# read in files and merge
fpath=paste0(input_dir,file_list[[1]])
merged_df=read.csv(fpath,sep="\t")
merged_df$sample="kd-sh1"

fpath=paste0(input_dir,file_list[[2]])
tmp_df=read.csv(fpath,sep="\t")
tmp_df$sample="kd-sh2"
merged_df=full_join(merged_df,tmp_df)

# remove values without z scores
merged_df=merged_df[complete.cases(merged_df$Activation.z.score),]
```

## Analysis  {.tabset}

Plots and datatables are created for each sample, with the top 1-3 molecules per molecule type.

### kd-sh1
```{r, echo=FALSE, message=FALSE,warning=FALSE}
sample_id="kd-sh1"
nmol_include=1
main_function(sample_id,merged_df,nmol_include)

nmol_include=2
main_function(sample_id,merged_df,nmol_include)

nmol_include=3
main_function(sample_id,merged_df,nmol_include)
```

### kd-sh2
```{r, echo=FALSE, message=FALSE,warning=FALSE}
sample_id="kd-sh2"
nmol_include=1
main_function(sample_id,merged_df,nmol_include)

nmol_include=2
main_function(sample_id,merged_df,nmol_include)

nmol_include=3
main_function(sample_id,merged_df,nmol_include)
```
